# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-DProfLB
version:      0.01
version_from: DProfLB.pm
installdirs:  site
requires:
    POSIX:                         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
